### ISSUE TITLE
Unable to run App Image Pool on Fedora Silverblue

### ISSUE THREAD

**Issue by DaviMG07** [prateekmedia/appimagepool#115]
I tried running both the Flatpak and AppImage versions of the application, but it only displays a blank page.
I'm getting these errors:

** (appimagepool:4264): WARNING **: 18:02:02.085: Failed to start Flutter renderer: Unable to create a GL context

** (appimagepool:4264): WARNING **: 18:02:03.948: Unable to retrieve framework response: No engine to send to

** (appimagepool:4264): WARNING **: 18:02:03.972: Unable to retrieve framework response: No engine to send to

**Comment by DaviMG07** [comment]
I saw a similar issue on flutter github [here](https://github.com/flutter/flutter/issues/106941). Using Flatseal, I exported the variable export LIBGL_ALWAYS_SOFTWARE=1. At least it shows the application now, but it's still not running as expected.

A comparison between how flatseal and appimagepool are being displayed. the app doesn't follow the desktop theme, nor the size:
![Screenshot from 2024-03-12 18-28-42](https://github.com/prateekmedia/appimagepool/assets/139729660/467ea1d2-74e6-4480-ac2a-8ecce67c765f)

Running from terminal I got that:

flutter: PathNotFoundException: Cannot open file, path = '/var/home/davi/.var/app/io.github.prateekmedia.appimagepool/config/dconf/user' (OS Error: No such file or directory, errno = 2)
flutter: Unsupported operation: Unsupported clipPath child g
flutter: #0      debugPrintStack (package:flutter/src/foundation/assertions.dart:1209)
flutter: #1      FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:1028)
flutter: #2      FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1189)
flutter: #3      _Elements.clipPath (package:flutter_svg/src/svg/parser_state.dart:491)
flutter: #4      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:887)
flutter: <asynchronous suspension>
flutter: #5      SvgParser.parse (package:flutter_svg/parser.dart:27)
flutter: <asynchronous suspension>
flutter: #6      Svg.fromSvgString (package:flutter_svg/svg.dart:139)
flutter: <asynchronous suspension>
flutter: #7      Svg.svgPictureDecoder (package:flutter_svg/svg.dart:57)
flutter: <asynchronous suspension>
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
