### ISSUE TITLE
Unable to switch download directory

### ISSUE THREAD

**Issue by Allan-Shand** [prateekmedia/appimagepool#16]
![appimagepoolscreenshot](https://user-images.githubusercontent.com/2791233/146502131-859e0e0e-0009-4bfe-982b-933bcc8cd8a2.png)

Using Manjaro KDE I am unable to switch download directory

Appimage stable 4.4.0

**Comment by mijorus** [comment]
I have the same issue as well, PopOS 20.04

Error log in the console
```
Gtk-Message: 09:15:36.892: Failed to load module "appmenu-gtk-module"
Gtk-Message: 09:15:36.935: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:15:36.936: Failed to load module "canberra-gtk-module"
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = '/home/altravia/.var/app/io.github.prateekmedia.appimagepool/config/dconf/user' (OS Error: File o directory non esistente, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356)
#1      _rootRunUnary (dart:async/zone.dart:1436)
<asynchronous suspension>
#2      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#3      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#4      DConfClient.read (package:gsettings/src/dconf_client.dart:85)
<asynchronous suspension>
#5      GSettings.get (package:gsettings/src/gsettings.dart:71)
<asynchronous suspension>
#6      _RawDecoratedWindowButtonState.getTheme (package:window_decorations/src/decorated_button.dart:159)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = '/home/altravia/.var/app/io.github.prateekmedia.appimagepool/config/dconf/user' (OS Error: File o directory non esistente, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356)
#1      _rootRunUnary (dart:async/zone.dart:1436)
<asynchronous suspension>
#2      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#3      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#4      DConfClient.read (package:gsettings/src/dconf_client.dart:85)
<asynchronous suspension>
#5      GSettings.get (package:gsettings/src/gsettings.dart:71)
<asynchronous suspension>
#6      _RawDecoratedWindowButtonState.getTheme (package:window_decorations/src/decorated_button.dart:159)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = '/home/altravia/.var/app/io.github.prateekmedia.appimagepool/config/dconf/user' (OS Error: File o directory non esistente, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356)
#1      _rootRunUnary (dart:async/zone.dart:1436)
<asynchronous suspension>
#2      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#3      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#4      DConfClient.read (package:gsettings/src/dconf_client.dart:85)
<asynchronous suspension>
#5      GSettings.get (package:gsettings/src/gsettings.dart:71)
<asynchronous suspension>
#6      _GtkHeaderBarMinimalState.initState.<anonymous closure> (package:gtk/src/widgets/gtk_header_bar_minimal.dart:127)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = '/home/altravia/.var/app/io.github.prateekmedia.appimagepool/config/dconf/user' (OS Error: File o directory non esistente, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356)
#1      _rootRunUnary (dart:async/zone.dart:1436)
<asynchronous suspension>
#2      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#3      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#4      DConfClient.read (package:gsettings/src/dconf_client.dart:85)
<asynchronous suspension>
#5      GSettings.get (package:gsettings/src/gsettings.dart:71)
<asynchronous suspension>
#6      _RawDecoratedWindowButtonState.getTheme (package:window_decorations/src/decorated_button.dart:159)
<asynchronous suspension>

flutter: Unsupported operation: Unsupported clipPath child g
flutter: #0      debugPrintStack (package:flutter/src/foundation/assertions.dart:1157)
flutter: #1      FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:978)
flutter: #2      FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1138)
flutter: #3      _Elements.clipPath (package:flutter_svg/src/svg/parser_state.dart:510)
flutter: #4      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:854)
flutter: <asynchronous suspension>
flutter: #5      SvgParser.parse (package:flutter_svg/parser.dart:27)
flutter: <asynchronous suspension>
flutter: #6      Svg.fromSvgString (package:flutter_svg/svg.dart:131)
flutter: <asynchronous suspension>
flutter: #7      Svg.svgPictureDecoder (package:flutter_svg/svg.dart:55)
flutter: <asynchronous suspension>
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = '/home/altravia/.var/app/io.github.prateekmedia.appimagepool/config/dconf/user' (OS Error: File o directory non esistente, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356)
#1      _rootRunUnary (dart:async/zone.dart:1436)
<asynchronous suspension>
#2      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#3      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#4      DConfClient.read (package:gsettings/src/dconf_client.dart:85)
<asynchronous suspension>
#5      GSettings.get (package:gsettings/src/gsettings.dart:71)
<asynchronous suspension>
#6      _RawDecoratedWindowButtonState.getTheme (package:window_decorations/src/decorated_button.dart:159)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: Couldn't find the executable zenity in the path.
#0      isExecutableOnPath (package:file_picker/src/utils.dart:60)
<asynchronous suspension>
#1      FilePickerLinux._getPathToExecutable (package:file_picker/src/file_picker_linux.dart:95)
<asynchronous suspension>
#2      FilePickerLinux.getDirectoryPath (package:file_picker/src/file_picker_linux.dart:55)
<asynchronous suspension>
#3      PrefsWidget.build.<anonymous closure> (package:appimagepool/widgets/prefs_dialog.dart:125)
<asynchronous suspension>
```

**Comment by vetro21** [comment]
@Allan-Shand I solved it by installing zenity

```
appimagepool-x86_64.AppImage %u
flutter: Unsupported operation: Unsupported clipPath child g
flutter: #0      debugPrintStack (package:flutter/src/foundation/assertions.dart:1157)
flutter: #1      FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:978)
flutter: #2      FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1138)
flutter: #3      _Elements.clipPath (package:flutter_svg/src/svg/parser_state.dart:510)
flutter: #4      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:854)
flutter: <asynchronous suspension>
flutter: #5      SvgParser.parse (package:flutter_svg/parser.dart:27)
flutter: <asynchronous suspension>
flutter: #6      Svg.fromSvgString (package:flutter_svg/svg.dart:131)
flutter: <asynchronous suspension>
flutter: #7      Svg.svgPictureDecoder (package:flutter_svg/svg.dart:55)
flutter: <asynchronous suspension>
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: Couldn't find the executable zenity in the path.

```

**Comment by 416d72** [comment]
> I solved it by installing zenity

Confirming this is the solution in my case.
I'm using Kubuntu 21.10

**Comment by Allan-Shand** [comment]
@vetro21 Installing zenity solved the issue for me too on Manjaro Qonos 21.2 rc

I will leave this issue open until this is fixed

**Comment by rijnhard** [comment]
also seeing this in the flatpak.

**Comment by mnipritom** [comment]
I have made a pull request to miguelpruivo/flutter_file_picker#932 that fixes this issue on KDE while running appimage version of this application. As for the instances where `zenity` is already installed but not being called, might be a flatpak permissions related issue, although I'm not sure.

**Comment by mnipritom** [comment]
https://user-images.githubusercontent.com/10971185/148632436-f256bc49-6d84-4214-93c7-ca0c02d3dcd9.mp4

**Comment by mnipritom** [comment]
Flatpak invokes `zenity` now, but doesn't get file system permissions
```fish
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] 
Unhandled Exception: FileSystemException: Cannot open file, 
path = '/home/scholar/.var/app/io.github.prateekmedia.appimagepool/config/dconf/user' 
(OS Error: No such file or directory, errno = 2)
```

Flatpak version: 4.9.0

**Comment by prateekmedia** [comment]
I think this should be fixed in v5, if you still face it I will reopen this issue. also if you are using flatpak I would suggest you to use AppImage instead.
